version: "3.9"

x-backend-base: &backend-base
  build: .
  environment:
    - SIDEKIQ_REDIS_URL=redis://redis:6379/0
    - RAILS_ENV=development

services:
  migrate:
    <<: *backend-base
    command: bundle exec rake db:migrate
    # intentionally not setting SIDEKIQ_MEDIA_STREAMS_REDIS_URL

  web:
    labels:
      shipyard.route: '/'
    build:
      context: .
    ports:
      - '80'
