apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-demo
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrate
        image: rails-migrate-fail-demo:latest
        command: ["ruby", "script.rb"]
        env:
          - name: SIDEKIQ_REDIS_URL
            value: redis://redis:6379/0
      # no SIDEKIQ_MEDIA_STREAMS_REDIS_URL set, so it will KeyError
